version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7.3
        environment:
          PIPENV_VENV_IN_PROJECT: true
    steps:
      - checkout
      - restore_cache:
          key: deps1-{{ checksum "Pipfile.lock" }}
      - run:
          command: pipenv install --dev --deploy
      - save_cache:
          key: deps1-{{ checksum "Pipfile.lock" }}
          paths:
            - ".venv"
      - run:
          command: pipenv run python -m pytest
